---
- name: create network and subnet
  hosts: openstack
  tasks:
    - name: create network
      os_network:
        auth:
          auth_url: "{{ auth_url }}"
          username: "{{ username }}"
          password: "{{ password }}"
          project_name: "{{ project_name }}"
          project_domain_name: "{{ project_domain_name }}"
          user_domain_name: "{{ user_domain_name }}"
        state: present
        name: ansible_network
        provider_network_type: geneve
        provider_segmentation_id: 2
      register: result
    - name: create subnet
      os_subnet:
        auth:
          auth_url: "{{ auth_url }}"
          username: "{{ username }}"
          password: "{{ password }}"
          project_name: "{{ project_name }}"
          project_domain_name: "{{ project_domain_name }}"
          user_domain_name: "{{ user_domain_name }}"
        name: ansible_subnet
        state: present
        network_name: "{{ result.network.name }}"
        cidr: 192.168.0.0/24

        
        